ingestion_config=[
    {
        "source":"crm",
        "path":"/Volumes/sales/bronze/crm/cust_info.csv",
        "table":"sales.bronze.cust_info"
    },
    {
        "source":"crm",
        "path":"/Volumes/sales/bronze/crm/prd_info.csv",
        "table":"sales.bronze.prd_info"
    },
    {
        "source":"crm",
        "path":"/Volumes/sales/bronze/crm/sales_details.csv",
        "table":"sales.bronze.sales_details"
    },
    {
        "source":"erp",
        "path":"/Volumes/sales/bronze/erp/CUST_AZ12.csv",
        "table":"sales.bronze.CUST_AZ12"
    },
    {
        "source":"erp",
        "path":"/Volumes/sales/bronze/erp/LOC_A101.csv",
        "table":"sales.bronze.LOC_A101"
    },
    {
        "source":"erp",
        "path":"/Volumes/sales/bronze/erp/PX_CAT_G1V2.csv",
        "table":"sales.bronze.PX_CAT_G1V2"
    }
]